
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/trades?createDatabaseIfNotExist=true&rewriteBatchedStatements=true&allowMultiQueries=true
    username: root
    password: 123
  sql:
    init:
      mode: always

mybatis:
  type-aliases-package: me.yorick.poc.mybatis.model
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    default-executor-type: BATCH
    #log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    
logging:
  level:
    me.yorick.poc: INFO
    #org.apache.ibatis: DEBUG